server:
  port: 8888

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka

spring:
  application:
    name: config-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./configFiles

#server:
#  port: 8888
#
#spring:
#  application:
#    name: config-service
#  cloud:
#    config:
#      server:
#        git:
#          uri: file:///Users/ksh/OneDrive - dongguk.edu/SoungHo/git-local-reop